[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[project]
name = "python-eigen-rs"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]
dependencies = ["numpy"]

[tool.maturin]
features = ["pyo3/extension-module"]
